# Generated by Django 3.1.7 on 2021-04-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('Username', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField()),
            ],
        ),
    ]
