# Generated by Django 3.1.7 on 2021-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
