# Generated by Django 3.1.7 on 2021-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userinformation_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeName', models.TextField()),
            ],
        ),
    ]
