# Generated by Django 3.1.7 on 2021-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_collegename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='Image',
            field=models.ImageField(default='', upload_to='accounts/images/'),
        ),
    ]
