# Generated by Django 3.1.7 on 2021-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userinformation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='Name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='Image',
            field=models.ImageField(default='', upload_to='accounts/images'),
        ),
    ]
