# Generated by Django 3.1.7 on 2021-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210414_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='Skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
